version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile-backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: {}

