# Generated by Django 4.2.11 on 2024-04-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_comment_options_alter_locationimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='image',
            field=models.ImageField(upload_to='location_images/'),
        ),
    ]
